name: Project Carz Schedule Crawler data
on:
  schedule:
    - cron: 0 0 * * 6 # Runs at 12 AM (midnight) every Saturday
    # - cron: '* * * * *' # Runs every minute

  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/nestjs-carz-crawler"
          token: ${{ secrets.GH_TOKEN }}
          ref: "main"
