name: Project Carz Schedule Crawler data
on:
  schedule:
    - cron: 0 0 * * 6 # Runs at 12 AM (midnight) every Saturday
    # - cron: '* * * * *' # Runs every minute

  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/nestjs-carz-crawler"
          token: ${{ secrets.GH_TOKEN }}
          ref: "main"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --force
      - name: Init env
        env:
          PORT: ${{vars.PORT}}
          MONGODB_URL: ${{vars.MONGODB_URL}}
          MONGO_DB_NAME: ${{vars.MONGO_DB_NAME}}
          RABBITMQ_CRAWLER_QUEUE: ${{vars.RABBITMQ_CRAWLER_QUEUE}}
          RABBITMQ_URL: ${{vars.RABBITMQ_URL}}
        run: |
          echo "PORT=$PORT" >> .env
          echo "MONGODB_URL=$MONGODB_URL" >> .env
          echo "MONGO_DB_NAME=$MONGO_DB_NAME" >> .env
          echo "RABBITMQ_CRAWLER_QUEUE=$RABBITMQ_CRAWLER_QUEUE" >> .env
          echo "RABBITMQ_URL=$RABBITMQ_URL" >> .env
      - name: Build NestJS application
        run: npm run build
      - name: Start NestJS application
        run: npm run start:prod &
      - name: Wait for npm start to start
        run: sleep 10
      - name: Run app and crawl data
        env:
          PORT: ${{vars.PORT}}
        run: |
          curl -X GET http://localhost:$PORT/api/write-to-csv
      - name: Push changes
        run: |
          touch cars-data-crawler.csv
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add cars-data-crawler.csv
          git commit -m "Update data"
          git push
