name: Project Carz Schedule Crawler data
on:
  schedule:
    - cron: 0 0 * * 6 # Runs at 12 AM (midnight) every Saturday
    # - cron: '* * * * *' # Runs every minute

  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false
permissions:
  contents: write
  actions: write
jobs:
  pre-deployment:
    name: Pre Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Notification to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "🚀 - Start crawling data Khmer24..."
  crawler:
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        os:
          [
            { name: ubuntu-latest, chunk: 0 },
            { name: ubuntu-latest, chunk: 1 },
            { name: ubuntu-latest, chunk: 2 },
            { name: ubuntu-latest, chunk: 3 },
            { name: ubuntu-latest, chunk: 4 },
            { name: ubuntu-latest, chunk: 5 },
            { name: ubuntu-latest, chunk: 6 },
            { name: ubuntu-latest, chunk: 7 },
            { name: ubuntu-latest, chunk: 8 },
            { name: ubuntu-latest, chunk: 9 },
          ]
    runs-on: ${{ matrix.os.name }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/nestjs-carz-crawler"
          token: ${{ secrets.GH_TOKEN }}
          ref: "main"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: npm install --force
      - name: Start NestJS application
        run: |
          node -v
          echo "const crawler = require('./crawl'); crawler.createData(${{ matrix.os.chunk }});" > crawler${{ matrix.os.chunk }}.js
          node crawler${{ matrix.os.chunk }}

      - name: Push changes

        run: |
          du -h ./${{ matrix.os.chunk }}.cars-data-crawler.csv
          git branch -d feat/data-crawler-${{ matrix.os.chunk }}
          git push origin --delete feat/data-crawler-${{ matrix.os.chunk }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git brand -d feat/data-crawler-${{ matrix.os.chunk }}
          git checkout -b feat/data-crawler-${{ matrix.os.chunk }}
          git add ./${{ matrix.os.chunk }}.cars-data-crawler.csv
          git commit -m "save crawl data" > /dev/null 2>&1 || echo "No changes to commit"
          git push --set-upstream origin feat/data-crawler-${{ matrix.os.chunk }}

      - name: Failure notification
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "💣 - Failure crawling data Khmer24(${{ matrix.os.chunk }})."
  sendNotifcationResult:
    name: Send Notification Result
    runs-on: ubuntu-latest
    steps:
      - name: Succesfully notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "✅ - Success crawling data Khmer24(${{ matrix.os.chunk }}). "
